export const apidata = [
  {
    date: "2020-05-30",
    customer_name: "Khondokar Khairul Bashar",
    product: "MotoTracker",
    district: "Dhaka",
    customer_work_area: "Delivery",
    order_quantity: 1,
  },
  {
    date: "2020-06-02",
    customer_name: "Khondokar Belayet Hussain",
    product: "CarTracker",
    district: "Sylhet",
    customer_work_area: "Delivery",
    order_quantity: 9,
  },
  {
    date: "2020-06-05",
    customer_name: "ABM Maidul Islam",
    product: "MotoTracker",
    district: "Sylhet",
    customer_work_area: "Logistics",
    order_quantity: 10,
  },
  {
    date: "2020-06-04",
    customer_name: "Syed Mustak Ahamed",
    product: "AssetLock",
    district: "Dhaka",
    customer_work_area: "Logistics",
    order_quantity: 6,
  },
  {
    date: "2020-06-02",
    customer_name: "Mohammad Belal hussain",
    product: "AssetLock",
    district: "Rangpur",
    customer_work_area: "Telecom",
    order_quantity: 8,
  },
  {
    date: "2020-06-06",
    customer_name: "Mohammad Ishtiyak ahmed",
    product: "CarTracker",
    district: "Rangpur",
    customer_work_area: "Logistics",
    order_quantity: 8,
  },
  {
    date: "2020-06-01",
    customer_name: "Syed Rashidul Haque",
    product: "MotoTracker",
    district: "Dhaka",
    customer_work_area: "FMCG",
    order_quantity: 1,
  },
  {
    date: "2020-06-02",
    customer_name: "MD. Belal hussain",
    product: "AssetLock",
    district: "Chittagong",
    customer_work_area: "FMCG",
    order_quantity: 10,
  },
  {
    date: "2020-06-07",
    customer_name: "Sheikh Nafisul Islam",
    product: "EagleCam",
    district: "Dhaka",
    customer_work_area: "Telecom",
    order_quantity: 6,
  },
  {
    date: "2020-06-03",
    customer_name: "Khondokar Kayyum",
    product: "MotoTracker",
    district: "Chittagong",
    customer_work_area: "Telecom",
    order_quantity: 9,
  },
  {
    date: "2020-06-06",
    customer_name: "Syed Khairul Bashar",
    product: "AssetLock",
    district: "Sylhet",
    customer_work_area: "Sales & Distribution",
    order_quantity: 4,
  },
  {
    date: "2020-06-06",
    customer_name: "Khondokar Muhit",
    product: "CarTracker",
    district: "Sylhet",
    customer_work_area: "Delivery",
    order_quantity: 6,
  },
  {
    date: "2020-06-05",
    customer_name: "Mohammad Mustak Ahamed",
    product: "EagleCam",
    district: "Rangpur",
    customer_work_area: "Logistics",
    order_quantity: 7,
  },
  {
    date: "2020-06-07",
    customer_name: "Mohammad Muhit",
    product: "MotoTracker",
    district: "Rangpur",
    customer_work_area: "Delivery",
    order_quantity: 4,
  },
  {
    date: "2020-06-05",
    customer_name: "Mohammad Anisul Haque",
    product: "CarTracker",
    district: "Sylhet",
    customer_work_area: "Sales & Distribution",
    order_quantity: 8,
  },
  {
    date: "2020-06-06",
    customer_name: "MD. Rafiul Amin",
    product: "EagleCam",
    district: "Chittagong",
    customer_work_area: "Logistics",
    order_quantity: 4,
  },
  {
    date: "2020-06-01",
    customer_name: "Mohammad Rafiqul Islam",
    product: "AssetLock",
    district: "Chittagong",
    customer_work_area: "Telecom",
    order_quantity: 2,
  },
  {
    date: "2020-06-03",
    customer_name: "AKM Kayyum",
    product: "EagleCam",
    district: "Rangpur",
    customer_work_area: "Telecom",
    order_quantity: 1,
  },
  {
    date: "2020-06-01",
    customer_name: "Syed Rafiul Amin",
    product: "MotoTracker",
    district: "Chittagong",
    customer_work_area: "Telecom",
    order_quantity: 9,
  },
  {
    date: "2020-06-03",
    customer_name: "Mohammad Rafayet Khan",
    product: "EagleCam",
    district: "Sylhet",
    customer_work_area: "Logistics",
    order_quantity: 6,
  },
  {
    date: "2020-06-07",
    customer_name: "AKM Ashikur Rahman",
    product: "EagleCam",
    district: "Sylhet",
    customer_work_area: "Sales & Distribution",
    order_quantity: 1,
  },
  {
    date: "2020-06-07",
    customer_name: "ABM Musa",
    product: "MotoTracker",
    district: "Dhaka",
    customer_work_area: "Telecom",
    order_quantity: 3,
  },
  {
    date: "2020-06-03",
    customer_name: "Mohammad Anisul Haque",
    product: "CarTracker",
    district: "Dhaka",
    customer_work_area: "FMCG",
    order_quantity: 10,
  },
  {
    date: "2020-06-04",
    customer_name: "Sheikh Ismail Hussain",
    product: "MotoTracker",
    district: "Rangpur",
    customer_work_area: "Sales & Distribution",
    order_quantity: 7,
  },
  {
    date: "2020-06-03",
    customer_name: "AKM Belayet Hussain",
    product: "MotoTracker",
    district: "Rangpur",
    customer_work_area: "Delivery",
    order_quantity: 5,
  },
  {
    date: "2020-05-30",
    customer_name: "ABM Ashikur Rahman",
    product: "EagleCam",
    district: "Chittagong",
    customer_work_area: "Telecom",
    order_quantity: 2,
  },
  {
    date: "2020-06-07",
    customer_name: "MD. Ishtiyak ahmed",
    product: "CarTracker",
    district: "Rangpur",
    customer_work_area: "Delivery",
    order_quantity: 4,
  },
  {
    date: "2020-06-06",
    customer_name: "ABM Ashikur Rahman",
    product: "MotoTracker",
    district: "Chittagong",
    customer_work_area: "Delivery",
    order_quantity: 6,
  },
  {
    date: "2020-06-03",
    customer_name: "ABM Khairul Bashar",
    product: "AssetLock",
    district: "Dhaka",
    customer_work_area: "Delivery",
    order_quantity: 5,
  },
  {
    date: "2020-06-01",
    customer_name: "Syed Rafayet Khan",
    product: "AssetLock",
    district: "Chittagong",
    customer_work_area: "Sales & Distribution",
    order_quantity: 4,
  },
  {
    date: "2020-06-04",
    customer_name: "Mohammad Khairul Bashar",
    product: "MotoTracker",
    district: "Dhaka",
    customer_work_area: "Telecom",
    order_quantity: 10,
  },
  {
    date: "2020-06-02",
    customer_name: "Khondokar Anisul Haque",
    product: "MotoTracker",
    district: "Dhaka",
    customer_work_area: "FMCG",
    order_quantity: 7,
  },
  {
    date: "2020-06-04",
    customer_name: "Khondokar Anisul Haque",
    product: "AssetLock",
    district: "Rangpur",
    customer_work_area: "Telecom",
    order_quantity: 8,
  },
  {
    date: "2020-06-07",
    customer_name: "MD. Shmim Hasan",
    product: "EagleCam",
    district: "Chittagong",
    customer_work_area: "Delivery",
    order_quantity: 6,
  },
  {
    date: "2020-06-03",
    customer_name: "MD. Anisul Haque",
    product: "EagleCam",
    district: "Chittagong",
    customer_work_area: "FMCG",
    order_quantity: 5,
  },
  {
    date: "2020-06-06",
    customer_name: "AKM Salehin",
    product: "AssetLock",
    district: "Sylhet",
    customer_work_area: "Delivery",
    order_quantity: 10,
  },
  {
    date: "2020-06-05",
    customer_name: "Khondokar Nafisul Islam",
    product: "AssetLock",
    district: "Rangpur",
    customer_work_area: "FMCG",
    order_quantity: 6,
  },
  {
    date: "2020-06-06",
    customer_name: "Sheikh Maidul Islam",
    product: "CarTracker",
    district: "Chittagong",
    customer_work_area: "Telecom",
    order_quantity: 2,
  },
  {
    date: "2020-06-03",
    customer_name: "AKM Rafiul Amin",
    product: "MotoTracker",
    district: "Rangpur",
    customer_work_area: "Logistics",
    order_quantity: 2,
  },
  {
    date: "2020-06-01",
    customer_name: "Sheikh Aminul Islam",
    product: "AssetLock",
    district: "Dhaka",
    customer_work_area: "Telecom",
    order_quantity: 6,
  },
  {
    date: "2020-06-05",
    customer_name: "Sheikh Anisul Haque",
    product: "EagleCam",
    district: "Rangpur",
    customer_work_area: "FMCG",
    order_quantity: 6,
  },
  {
    date: "2020-06-04",
    customer_name: "MD. Nafisul Islam",
    product: "EagleCam",
    district: "Sylhet",
    customer_work_area: "Sales & Distribution",
    order_quantity: 3,
  },
  {
    date: "2020-06-03",
    customer_name: "Mohammad Nafisul Islam",
    product: "MotoTracker",
    district: "Rangpur",
    customer_work_area: "FMCG",
    order_quantity: 7,
  },
  {
    date: "2020-06-07",
    customer_name: "MD. Nafisul Islam",
    product: "MotoTracker",
    district: "Dhaka",
    customer_work_area: "FMCG",
    order_quantity: 9,
  },
  {
    date: "2020-06-07",
    customer_name: "ABM Rafiqul Islam",
    product: "MotoTracker",
    district: "Dhaka",
    customer_work_area: "Telecom",
    order_quantity: 9,
  },
  {
    date: "2020-06-02",
    customer_name: "AKM Aminul Islam",
    product: "CarTracker",
    district: "Sylhet",
    customer_work_area: "Logistics",
    order_quantity: 1,
  },
  {
    date: "2020-06-01",
    customer_name: "Sheikh Khairul Bashar",
    product: "CarTracker",
    district: "Rangpur",
    customer_work_area: "Logistics",
    order_quantity: 3,
  },
  {
    date: "2020-06-07",
    customer_name: "Khondokar Khairul Bashar",
    product: "MotoTracker",
    district: "Rangpur",
    customer_work_area: "Logistics",
    order_quantity: 10,
  },
  {
    date: "2020-06-07",
    customer_name: "AKM Salehin",
    product: "EagleCam",
    district: "Dhaka",
    customer_work_area: "Delivery",
    order_quantity: 10,
  },
  {
    date: "2020-06-06",
    customer_name: "Sheikh Rafayet Khan",
    product: "AssetLock",
    district: "Sylhet",
    customer_work_area: "Delivery",
    order_quantity: 1,
  },
  {
    date: "2020-06-06",
    customer_name: "MD. Ashraful",
    product: "AssetLock",
    district: "Dhaka",
    customer_work_area: "Sales & Distribution",
    order_quantity: 1,
  },
  {
    date: "2020-06-03",
    customer_name: "MD. Rafiqul Islam",
    product: "CarTracker",
    district: "Chittagong",
    customer_work_area: "Delivery",
    order_quantity: 4,
  },
  {
    date: "2020-06-01",
    customer_name: "ABM Belayet Hussain",
    product: "CarTracker",
    district: "Dhaka",
    customer_work_area: "Sales & Distribution",
    order_quantity: 9,
  },
  {
    date: "2020-06-06",
    customer_name: "Mohammad Rafiqul Islam",
    product: "CarTracker",
    district: "Sylhet",
    customer_work_area: "Logistics",
    order_quantity: 7,
  },
  {
    date: "2020-06-03",
    customer_name: "Syed Mustak Ahamed",
    product: "EagleCam",
    district: "Sylhet",
    customer_work_area: "Delivery",
    order_quantity: 2,
  },
  {
    date: "2020-06-02",
    customer_name: "Syed Ashikur Rahman",
    product: "AssetLock",
    district: "Chittagong",
    customer_work_area: "Delivery",
    order_quantity: 1,
  },
  {
    date: "2020-06-04",
    customer_name: "AKM Ashikur Rahman",
    product: "AssetLock",
    district: "Rangpur",
    customer_work_area: "FMCG",
    order_quantity: 3,
  },
  {
    date: "2020-06-01",
    customer_name: "Mohammad Nafisul Islam",
    product: "MotoTracker",
    district: "Chittagong",
    customer_work_area: "Telecom",
    order_quantity: 9,
  },
  {
    date: "2020-06-06",
    customer_name: "Mohammad Musa",
    product: "MotoTracker",
    district: "Chittagong",
    customer_work_area: "Logistics",
    order_quantity: 8,
  },
  {
    date: "2020-06-01",
    customer_name: "Syed Kayyum",
    product: "EagleCam",
    district: "Sylhet",
    customer_work_area: "Delivery",
    order_quantity: 8,
  },
  {
    date: "2020-06-04",
    customer_name: "Syed Anisul Haque",
    product: "AssetLock",
    district: "Dhaka",
    customer_work_area: "FMCG",
    order_quantity: 8,
  },
  {
    date: "2020-06-01",
    customer_name: "Khondokar Anisul Haque",
    product: "AssetLock",
    district: "Chittagong",
    customer_work_area: "Sales & Distribution",
    order_quantity: 9,
  },
  {
    date: "2020-06-02",
    customer_name: "Syed Shmim Hasan",
    product: "EagleCam",
    district: "Rangpur",
    customer_work_area: "Delivery",
    order_quantity: 9,
  },
  {
    date: "2020-06-07",
    customer_name: "MD. Ismail Hussain",
    product: "CarTracker",
    district: "Sylhet",
    customer_work_area: "FMCG",
    order_quantity: 7,
  },
  {
    date: "2020-06-04",
    customer_name: "Sheikh Salehin",
    product: "CarTracker",
    district: "Sylhet",
    customer_work_area: "Telecom",
    order_quantity: 8,
  },
  {
    date: "2020-06-03",
    customer_name: "MD. Abdur Rahman",
    product: "MotoTracker",
    district: "Rangpur",
    customer_work_area: "Logistics",
    order_quantity: 1,
  },
  {
    date: "2020-06-01",
    customer_name: "AKM Rafiul Amin",
    product: "EagleCam",
    district: "Sylhet",
    customer_work_area: "FMCG",
    order_quantity: 10,
  },
  {
    date: "2020-06-03",
    customer_name: "Mohammad Shmim Hasan",
    product: "AssetLock",
    district: "Chittagong",
    customer_work_area: "Delivery",
    order_quantity: 8,
  },
  {
    date: "2020-06-02",
    customer_name: "MD. Maidul Islam",
    product: "MotoTracker",
    district: "Chittagong",
    customer_work_area: "Sales & Distribution",
    order_quantity: 1,
  },
  {
    date: "2020-06-02",
    customer_name: "AKM Rounak Hasan",
    product: "EagleCam",
    district: "Chittagong",
    customer_work_area: "FMCG",
    order_quantity: 5,
  },
];
